#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdataBCSSample
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TWCC")]
	public partial class TWCCClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSmallBlock(SmallBlock instance);
    partial void UpdateSmallBlock(SmallBlock instance);
    partial void DeleteSmallBlock(SmallBlock instance);
    #endregion
		
		public TWCCClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TWCCClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TWCCClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TWCCClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SmallBlock> SmallBlocks
		{
			get
			{
				return this.GetTable<SmallBlock>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SmallBlocks")]
	public partial class SmallBlock : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _FeatId;
		
		private System.Nullable<short> _Id;
		
		private string _CompanyID;
		
		private string _SmallBlock1;
		
		private System.Nullable<decimal> _SmallAC;
		
		private string _LargeBlock;
		
		private string _MineArea;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFeatIdChanging(long value);
    partial void OnFeatIdChanged();
    partial void OnIdChanging(System.Nullable<short> value);
    partial void OnIdChanged();
    partial void OnCompanyIDChanging(string value);
    partial void OnCompanyIDChanged();
    partial void OnSmallBlock1Changing(string value);
    partial void OnSmallBlock1Changed();
    partial void OnSmallACChanging(System.Nullable<decimal> value);
    partial void OnSmallACChanged();
    partial void OnLargeBlockChanging(string value);
    partial void OnLargeBlockChanged();
    partial void OnMineAreaChanging(string value);
    partial void OnMineAreaChanged();
    #endregion
		
		public SmallBlock()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeatId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long FeatId
		{
			get
			{
				return this._FeatId;
			}
			set
			{
				if ((this._FeatId != value))
				{
					this.OnFeatIdChanging(value);
					this.SendPropertyChanging();
					this._FeatId = value;
					this.SendPropertyChanged("FeatId");
					this.OnFeatIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="SmallInt")]
		public System.Nullable<short> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="NVarChar(10)")]
		public string CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this.OnCompanyIDChanging(value);
					this.SendPropertyChanging();
					this._CompanyID = value;
					this.SendPropertyChanged("CompanyID");
					this.OnCompanyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="SmallBlock", Storage="_SmallBlock1", DbType="NVarChar(50)")]
		public string SmallBlock1
		{
			get
			{
				return this._SmallBlock1;
			}
			set
			{
				if ((this._SmallBlock1 != value))
				{
					this.OnSmallBlock1Changing(value);
					this.SendPropertyChanging();
					this._SmallBlock1 = value;
					this.SendPropertyChanged("SmallBlock1");
					this.OnSmallBlock1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmallAC", DbType="Decimal(3,1)")]
		public System.Nullable<decimal> SmallAC
		{
			get
			{
				return this._SmallAC;
			}
			set
			{
				if ((this._SmallAC != value))
				{
					this.OnSmallACChanging(value);
					this.SendPropertyChanging();
					this._SmallAC = value;
					this.SendPropertyChanged("SmallAC");
					this.OnSmallACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LargeBlock", DbType="NVarChar(50)")]
		public string LargeBlock
		{
			get
			{
				return this._LargeBlock;
			}
			set
			{
				if ((this._LargeBlock != value))
				{
					this.OnLargeBlockChanging(value);
					this.SendPropertyChanging();
					this._LargeBlock = value;
					this.SendPropertyChanged("LargeBlock");
					this.OnLargeBlockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MineArea", DbType="NVarChar(10)")]
		public string MineArea
		{
			get
			{
				return this._MineArea;
			}
			set
			{
				if ((this._MineArea != value))
				{
					this.OnMineAreaChanging(value);
					this.SendPropertyChanging();
					this._MineArea = value;
					this.SendPropertyChanged("MineArea");
					this.OnMineAreaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
