//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReclamationDataTypes
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmallBlock
    {
        public long FeatId { get; set; }
        public Nullable<short> Id { get; set; }
        public string CompanyID { get; set; }
        public string SmallBlock1 { get; set; }
        public Nullable<decimal> SmallAC { get; set; }
        public string LargeBlock { get; set; }
        public string MineArea { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Geometry { get; set; }
    }
}
